version: "3.8"

services:
  mongodb:
    image: mongo:4.4
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
    volumes:
      - data:/data/db
    networks:
      - backendTravel

  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - backendTravel

volumes:
  data: {}

networks:
  backendTravel:
    name: backendTravel
